- Assets/Prefabs/Maps/Map_005.prefab
- Assets/Prefabs/Maps/Map_005.prefab.meta
- Assets/Scenes/LoginScene.unity
- ProjectSettings/TagManager.asset
Map_005 (성 입구 맵) prefab 추가
어떤 변경 사항이 있나요?
사냥터도 마을도 아닌 던전 입구 맵입니다.
자식 객체인 Collision을 통해 충돌 검사 하면 됩니다.
> [ADD] Map_005 성 입구 맵 추가

- 2D_MMO_Server/ServerCore/BitConverter.cpp
- 2D_MMO_Server/ServerCore/BitConverter.h
- 2D_MMO_Server/ServerCore/ServerCore.vcxproj
- 2D_MMO_Server/ServerCore/ServerCore.vcxproj.filters
BYTE 자료형에 관한 직렬화, 역직렬화 유틸 클래스 추가
추후 PacketManager와 PacketHandler 클래스에서 사용됨
어떤 변경 사항이 있나요?
destination의 startIndex위치에 value를 BYTE형식으로 직렬화 시킵니다.
```
bool TryWriteBytes(BYTE* destination, T value, uint32 startIndex)
```
BYTE* arr의 startIndex로부터 T자료형을 역직렬화 해 추출합니다.
```
T ToInt...(BYTE* arr, int32 startIndex)
T ToUInt...(BYTE* arr, int32 startIndex)
```
> [ADD] Bitconverter 유틸 클래스 추가

- 2D_MMO_Server/GameServer/GameServer.vcxproj
- 2D_MMO_Server/GameServer/GameServer.vcxproj.filters
- 2D_MMO_Server/GameServer/PacketHandler.cpp
- 2D_MMO_Server/GameServer/PacketHandler.h
- 2D_MMO_Server/GameServer/PacketManager.cpp
- 2D_MMO_Server/GameServer/PacketManager.h
- 2D_MMO_Server/GameServer/PlayerInfo_generated.h
- 2D_MMO_Server/GameServer/pch.h
- 2D_MMO_Server/ServerCore/Types.h
- 2D_MMO_Server/windows.flatc.binary/PlayerInfo.fbs
- 2D_MMO_Server/windows.flatc.binary/PlayerInfo_generated.h
PacketManager 패킷 직렬화, 역직렬화 유틸 클래스
PacketHandler 패킷 ID값에 따른 함수 네비게이션 클래스
어떤 변경 사항이 있나요?
PacketManager 클래스는 싱글톤으로 관리되며 나중에 추가될 PacketGenerator.bat 에 의해 자동화 될 클래스입니다.
PacketHandler 클래스는 static 클래스로 관리됩니다.
PacketManager 멤버 변수로 
unordered_map<int, function<void(PacketSession*, ByteRef&>> _handler;
가 있습니다.
해당 멤버 변수를 OnRecvPacket 멤버 함수를 통하여 패킷 핸들링을 합니다.
패킷을 받았을 때 처리할 함수(해당 함수를 통하여 패킷 핸들링)
```
void OnRecvPacket(PacketSession*, BYTE*);
```
패킷 직렬화 함수
Offset : FlatBufferBuilder에서 나온 데이터입니다.
PacketType : root.fbs 에서 사용되는 union(사용할 패킷 종류) 입니다.
```
ByteRef CreatePacket(Offset<T>&, FlatBufferBuilder&, PacketType);
```
> [ADD] PacketManager, PacketHandler 클래스 추가

- Assembly-CSharp.csproj
- Assets/Scenes/GameScene.unity
- Assets/Scripts/Controllers/CameraController.cs
- Assets/Scripts/Controllers/CameraController.cs.meta
- Assets/Scripts/Controllers/PlayerController.cs
- Assets/Scripts/Scene/BaseScene.cs
- Assets/Scripts/Scene/GameScene.cs
유저가 맵의 바깥쪽 영역을 볼 수 없도록 카메라 이동 제한
어떤 변경 사항이 있나요?
커밋 되돌리기로 인해 변경사항이 적용이 안돼서 PR을 다시 올렸습니다.
PR 내용은 #28 PR 참고 바랍니다.
> [ADD] 카메라 이동 제한

- 2D_MMO_Client/Assembly-CSharp.csproj
- 2D_MMO_Client/Assets/Scripts/Controllers/MonsterController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/MyPlayerController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/MyPlayerController.cs.meta
- 2D_MMO_Client/Assets/Scripts/Controllers/ObjectController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/PlayerController.cs
- 2D_MMO_Client/Assets/Scripts/Managers/ObjectManager.cs
- 2D_MMO_Client/Assets/Scripts/Packet/PacketHandler.cs
- 2D_MMO_Client/Assets/Scripts/Scene/GameScene.cs
- 2D_MMO_Client/Assets/Scripts/Session/ServerSession.cs
- 2D_MMO_Client/Assets/Scripts/Utils/Define.cs
서버로부터 받은 플레이어 스폰 및 디스폰 패킷을 클라이언트에서 처리
어떤 변경 사항이 있나요?
패킷 처리 부분은 PacketHandler.cs 참고해주시면 감사하겠습니다.
접속 되어있는 다른 클라이언트와 자신의 클라이언트에서 조작할 컨트롤러를 분리하기 위해
PlayerController와 MyPlayerController를 분리했습니다.
> [ADD] 클라이언트 플레이어 스폰 및 디스폰 처리

- 2D_MMO_Server/GameServer/PacketHandler.cpp
- 2D_MMO_Server/GameServer/PacketHandler.h
- 2D_MMO_Server/GameServer/PacketManager.cpp
- Common/fbs/Chat.fbs
- Common/fbs/Protocol.fbs
C_Chat 반환 패킷인 SC_Chat 구현
```
table SC_Chat {
playerInfo:PlayerInfo;
text:string;
}
```
구조체는 위와 같이 구성되어있습니다.
어떤 변경 사항이 있나요?
아직 player의 name은 구성되지 않은 상태여서 playerInfo를 만들 때
player의 ID만 넣었습니다.
> [ADD] SC_Chat 기능 구현

- 2D_MMO_Client/Assets/Scripts/Packet/PacketHandler.cs
- 2D_MMO_Client/Assets/Scripts/Packet/PacketManager.cs
- 2D_MMO_Client/Assets/Scripts/UI/ChatUIController.cs
게임 내 채팅 기능인 C_Chat 기능 구현
```
table C_Chat {
text:string;
}
```
구조체는 위와 같이 구성되어있습니다.
어떤 변경 사항이 있나요?
아직 Player의 name을 구성하지 않은 단계이기 때문에 채팅한 유저 식별은 Player의 ID로 했습니다.
> [ADD] C_Chat 기능 구현

- 2D_MMO_Client/Assets/Scripts/Controllers/MyPlayerController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/ObjectController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/PlayerController.cs
- 2D_MMO_Client/Assets/Scripts/Packet/PacketHandler.cs
- 2D_MMO_Client/Assets/Scripts/Packet/PacketManager.cs
클라이언트 스킬 동기화
어떤 변경 사항이 있나요?
1. 클라이언트에서 키 입력으로 스킬을 사용하면 스킬 아이디를 서버로 전송합니다.
2. 서버에서 스킬 아이디에 따라 피격 판정, 데미지 판정 등을 하고 클라이언트로 스킬 아이디를 다시 전송합니다.
3. 클라이언트는 서버로부터 스킬 아이디를 받아서 아이디에 맞는 스킬을 사용합니다.
> [ADD] 클라이언트 스킬 동기화

- 2D_MMO_Client/Assets/Editor/MapTool.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/MyPlayerController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/ObjectController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/PlayerController.cs
맵툴 파일 생성 경로 추가
어떤 변경 사항이 있나요?
Common/MapData 경로에도 맵 파일들을 생성하도록 수정했습니다.
Common 폴더 안에 MapData 폴더 생성하고 테스트해 주시면 감사하겠습니다.
키 입력 유무에 따라 바뀌는 bool 변수를 사용해 캐릭터의 이동 방향과 상태를 업데이트 하도록 수정했습니다.
간단한 수정 사항이라 이 PR에 포함해서 올렸습니다.
> [ADD] 맵툴 파일 생성 경로 추가

- 2D_MMO_Server/GameServer/Monster.cpp
서버에서 몬스터 스킬 AI 기능 추가
어떤 변경 사항이 있나요?
몬스터가 현재 바라보는 방향에서 사용할 수 있는 스킬 범위 안에 타겟이 있다면 타겟에게 데미지를 주는 방식입니다.
스킬은 쿨타임이 있어 일정 시간이 지나고 반복합니다.
> [ADD] 서버 몬스터 스킬 AI

- 2D_MMO_Client/Assets/Scripts/Controllers/MonsterController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/ObjectController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/PlayerController.cs
- 2D_MMO_Client/Assets/Scripts/Packet/PacketHandler.cs
- 2D_MMO_Client/ProjectSettings/TagManager.asset
SC_SKILL 패킷 핸들러 리팩터링
어떤 변경 사항이 있나요?
몬스터도 스킬을 사용할 수 있기 때문에 SC_SKILL 패킷에서 플레이어, 몬스터 컨트롤러의 부모 클래스인 게임 오브젝트 컨트롤러에서 스킬을 사용할 수 있도록 변경했습니다.
> [REFACTOR] SC_SKILL 패킷 핸들러 리팩터링

- 2D_MMO_Client/Assets/Scripts/Controllers/MonsterController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/PlayerController.cs
- Common/PacketGenerator.bat
- Common/fbs/InGame.fbs
클라이언트 실행 간단한 버그 수정
어떤 변경 사항이 있나요?
> [FIX] 클라이언트 실행 버그 수정

- 2D_MMO_Client/Assembly-CSharp-Editor.csproj
- 2D_MMO_Client/Assembly-CSharp.csproj
- 2D_MMO_Client/Assets/Scripts/Controllers/MonsterController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/MyPlayerController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/ObjectController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/PlayerController.cs
- 2D_MMO_Client/Assets/Scripts/Data/ContentsData.cs
- 2D_MMO_Client/Assets/Scripts/Managers/DataManager.cs
- 2D_MMO_Client/Assets/Scripts/Managers/Manager.cs
- 2D_MMO_Client/Assets/Scripts/Managers/ObjectManager.cs
- 2D_MMO_Client/Assets/Scripts/Packet/PacketHandler.cs
- 2D_MMO_Client/Assets/Scripts/Packet/PacketManager.cs
- 2D_MMO_Client/Packages/manifest.json
- 2D_MMO_Client/Packages/packages-lock.json
- Common/Client/PacketManager.cs
- Common/DBServer/PacketManager.cpp
- Common/Data/ContentsData/SkillData.json
- Common/Data/ContentsData/StatData.json
- Common/Server/PacketManager.cpp
- Common/fbs/InGame.fbs
- Common/fbs/Protocol.fbs
클라이언트에서 스킬 데이터 json 파일을 파싱하여 처리
서버에서 보내온 데미지 판정 클라이언트에서 처리
어떤 변경 사항이 있나요?
* 스킬 데이터 json 파일 파싱
Assets/Resources 경로가 아닌 다른 경로에서 json 파일을 불러와야 해서 유니티 엔진의 JsonUtility가 아닌 NewtonsSoft Json 3.2.1을 사용하여 json을 파싱하였습니다.
```
static Loader LoadJson<Loader, Key, Value>(string path) where Loader : ILoader<Key, Value>
{
string text = File.ReadAllText($"../Common/Data/ContentsData/{path}.json");
return Newtonsoft.Json.JsonConvert.DeserializeObject<Loader>(text);
}
```
<br>
* json 파일 로드
```
Manager.cs
static void Init()
{
if (_instance == null)
{
GameObject go = GameObject.Find("Manager");
if (go == null)
{
go = new GameObject { name = "Manager" };
go.AddComponent<Manager>();
}
DontDestroyOnLoad(go);
_instance = go.GetComponent<Manager>();
Network.Init();
// static이라서 싱글톤 객체를 만들지 않음 …
```
> [ADD] 클라이언트 컨텐츠 데이터 json 파싱 및 데미지 판정

- 2D_MMO_Server/GameServer/GameObject.cpp
- 2D_MMO_Server/GameServer/GameObject.h
- 2D_MMO_Server/GameServer/GameRoom.cpp
- 2D_MMO_Server/GameServer/GameRoom.h
- 2D_MMO_Server/GameServer/GameServer.cpp
- 2D_MMO_Server/GameServer/GameServer.vcxproj
- 2D_MMO_Server/GameServer/GameServer.vcxproj.filters
- 2D_MMO_Server/GameServer/Map.h
- 2D_MMO_Server/GameServer/Monster.cpp
- 2D_MMO_Server/GameServer/ObjectManager.cpp
- 2D_MMO_Server/GameServer/ObjectManager.h
- 2D_MMO_Server/GameServer/Player.cpp
- 2D_MMO_Server/GameServer/Projectile.cpp
- 2D_MMO_Server/GameServer/Projectile.h
- Common/Data/ContentsData/SkillData.json
투사체(화살) 공격 서버에서 처리
어떤 변경 사항이 있나요?
* 화살 생성
1. 클라이언트로부터 C_SKILL 패킷을 받으면 HandleSkill() 함수에서 스킬을 타입에 따라 다르게 처리합니다.
2. 스킬 타입이 원거리 공격이면 투사체(화살) 오브젝트 아이디를 생성하고 투사체 정보를 넣어줍니다.
3. 그 다음 생성된 투사체를 현재 룸에 입장 시킵니다.
```
case SkillType_SKILL_PROJECTILE:
{
shared_ptr<Projectile> projectile = ObjectManager::Instance().Add<Projectile>();
if (projectile == nullptr)
{
return;
}
// 플레이어 앞에 화살 생성
Vector2Int FrontCell = player->GetFrontCellPos();
projectile->SetOwner(player);
projectile->SetOwnerPos(player->GetObjectPosX(), player->GetObjectPosY());
projectile->SetSkillData(skillData);
projectile->SetObjectInfo(projectile->GetObjectId(), "Projectile" + to_string(projectile->GetObjectId()));
projectile->SetPosInfo(FrontCell.X, FrontCell.Y, ObjectState_MOVING, player->GetObjectMoveDir()); …
```
> [ADD] 서버 화살 공격 처리

- 2D_MMO_Client/Assembly-CSharp.csproj
- 2D_MMO_Client/Assets/Resources/Animations/Player/BOW_DOWN.anim
- 2D_MMO_Client/Assets/Resources/Animations/Player/BOW_DOWN.anim.meta
- 2D_MMO_Client/Assets/Resources/Animations/Player/BOW_RIGHT.anim
- 2D_MMO_Client/Assets/Resources/Animations/Player/BOW_RIGHT.anim.meta
- 2D_MMO_Client/Assets/Resources/Animations/Player/BOW_UP.anim
- 2D_MMO_Client/Assets/Resources/Animations/Player/BOW_UP.anim.meta
- 2D_MMO_Client/Assets/Resources/Animations/Player/PlayerAnimController.controller
- 2D_MMO_Client/Assets/Resources/Prefabs/Items.meta
- 2D_MMO_Client/Assets/Resources/Prefabs/Items/Arrow.prefab
- 2D_MMO_Client/Assets/Resources/Prefabs/Items/Arrow.prefab.meta
- 2D_MMO_Client/Assets/Scripts/Controllers/MyPlayerController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/PlayerController.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/ProjectileController.cs
- 2D_MMO_Client/Assets/Scripts/Managers/NetworkManager.cs
- 2D_MMO_Client/Assets/Scripts/Managers/ObjectManager.cs
클라이언트에서 화살 공격 처리
화살 프리팹 추가 및 플레이어 화살 공격 애니메이션 추가
어떤 변경 사항이 있나요?
* 화살 생성
1. 서버로부터 SC_SPAWN 패킷을 받으면 오브젝트의 타입에 따라 게임 오브젝트를 생성합니다.
2. 오브젝트 타입이 투사체라면 화살에 해당하는 프리팹을 로드하여 게임 오브젝트를 생성합니다.
3. 해당 오브젝트의 컴포넌트인 ProjectileController에 화살에 대한 값을 설정합니다.
```
// 생략
else if (objType == GameObjectType.PROJECTILE)
{
GameObject projectileOriginal = Resources.Load<GameObject>("Prefabs/Items/Arrow");
GameObject projectile = UnityEngine.Object.Instantiate(projectileOriginal);
projectile.name = info.Name;
_objects.Add(info.ObjectId, projectile);
ProjectileController pc = projectile.GetComponent<ProjectileController>();
pc.Id = info.ObjectId;
pc.CellPos = new Vector3Int(info.PosInfo.Value.PosX, info.PosInfo.Value.PosY, 0);
pc.MoveDir = (Define.MoveDir)info.PosInfo.Value.MoveDir;
pc.State = …
```
> [ADD] 클라이언트 화살 공격 처리

- 2D_MMO_Server/ServerCore/ServerCore.vcxproj
- 2D_MMO_Server/ServerCore/ServerCore.vcxproj.filters
서버코어 프로젝트가 format.cpp 파일 인식이 안되서 빌드 오류나던 버그를 수정했습니다.
어떤 변경 사항이 있나요?
> [FIX] 서버코어 프로젝트 format.cpp 인식 누락 수정

- 2D_MMO_Server/DBServer/DBServer.vcxproj
- 2D_MMO_Server/DBServer/DBServer.vcxproj.filters
- 2D_MMO_Server/DBServer/Login.cpp
- 2D_MMO_Server/DBServer/Manager.cpp
- 2D_MMO_Server/DBServer/Manager.h
- 2D_MMO_Server/DBServer/PacketHandler.h
- 2D_MMO_Server/DBServer/PacketManager.cpp
- 2D_MMO_Server/DBServer/pch.h
> [ADD] 로그인 기능 추가

- Common/PacketGenerator.bat
- Common/fbs/InGame.fbs
- Common/fbs/Login.fbs
- Common/fbs/Protocol.fbs
클라, 게임서버 DB서버에서 사용하는 Login 패킷 프로토콜 추가
어떤 변경 사항이 있나요?
해당 패킷들에 관한 로직은 이전 PR을 참고해주세요
> [ADD] Login 프로토콜 추가

- 2D_MMO_Server/DBServer/Login.cpp
dbId의 자료형을 SQLINTEGER에서 SQLBIGINT로 수정했습니다.
어떤 변경 사항이 있나요?
> [FIX] SD_SIGNINHandler dbId 자료형 오류 수정

- 2D_MMO_Server/GameServer/Login.cpp
password 변수를 id값으로 초기화 하던 문제를 수정했습니다.
어떤 변경 사항이 있나요?
> [FIX] C_SIGNUPHandler

- 2D_MMO_Server/GameServer/ClientSession.cpp
- 2D_MMO_Server/GameServer/ContentsData.cpp
- 2D_MMO_Server/GameServer/ContentsData.h
- 2D_MMO_Server/GameServer/DataManager.cpp
- 2D_MMO_Server/GameServer/DataManager.h
- 2D_MMO_Server/GameServer/GameRoom.cpp
- 2D_MMO_Server/GameServer/GameRoom.h
- 2D_MMO_Server/GameServer/GameServer.vcxproj
- 2D_MMO_Server/GameServer/GameServer.vcxproj.filters
- 2D_MMO_Server/GameServer/Item.cpp
- 2D_MMO_Server/GameServer/Item.h
- 2D_MMO_Server/GameServer/ItemManager.cpp
- 2D_MMO_Server/GameServer/ItemManager.h
- 2D_MMO_Server/GameServer/PacketHandler.cpp
- 2D_MMO_Server/GameServer/PacketHandler.h
- 2D_MMO_Server/GameServer/PacketManager.cpp
- 2D_MMO_Server/GameServer/Player.cpp
- 2D_MMO_Server/GameServer/Player.h
- Common/Data/ContentsData/ItemData.json
- Common/fbs/InGame.fbs
- Common/fbs/Protocol.fbs
서버에서 아이템 생성 후 클라이언트로 아이템 리스트 패킷 전송 기능 추가
어떤 변경 사항이 있나요?
* 아이템 생성
아이템에 대한 정보는 ItemData.json 파일을 파싱해서 서버에서 사용합니다.
파싱에 대한 내용은 #62 PR 참고해주시기 바랍니다.
```
ItemData.json
{
"weapons": [
{
"ID": 1,
"Name": "BeginnerSword",
"WeaponType": "WEAPON_SWORD",
"Damage": 5,
"IconPath":  "UI_Images/UI_Sword"
},
// 생략
}
```
<br>
TemplateID(json 파일에서는 ID에 해당)에 따라 서버에서 아이템을 생성합니다.
```
shared_ptr<Item> Item::MakeItem(int32 templateId)
{
shared_ptr<Item> item = nullptr;
shared_ptr<ItemData> itemData = nullptr;
auto iter = DataManager::Items.find(templateId);
if (iter != DataManager::Items.end())
{
itemData = iter->second;
}
if (itemData == nullptr)
{
return nullptr;
}
switch (itemData->ItemType)
{
case ItemType_ITEM_WEAPON:
item = make_shared<Weapon>(templateId);
break;
case ItemType_ITEM_ARMOR:
item = …
```
> [ADD] 서버에서 아이템 생성 및 아이템 리스트 패킷 전송

- 2D_MMO_Client/Assets/Scripts/Contents/Item.cs
- 2D_MMO_Client/Assets/Scripts/Controllers/MyPlayerController.cs
- 2D_MMO_Client/Assets/Scripts/Managers/InventoryManager.cs
- 2D_MMO_Client/Assets/Scripts/Packet/PacketHandler.cs
- 2D_MMO_Client/Assets/Scripts/Packet/PacketManager.cs
- 2D_MMO_Client/Assets/Scripts/UI/InventoryUIController.cs
- Common/fbs/InGame.fbs
- Common/fbs/Protocol.fbs
클라이언트 인벤토리 창에서 장비 착용 후 장비에 따라 스킬이 달라지는 기능 추가
어떤 변경 사항이 있나요?
* 장비 착용
인벤토리 창에서 무기를 드래그 앤 드랍으로 장비 창의 무기 슬롯에 내려놓으면 해당 아이템의 정보(게임오브젝트 ID, 착용여부)를 서버로 전송합니다.
```
private void PointerCaptureOutHandler(PointerCaptureOutEvent evt)
{
// -- 생략 --
// 착용하려는 아이템이 무기이고 아이템이 무기 슬롯에 있으면 패킷 전송
string iconName = item.style.backgroundImage.value.ToString();
if (item.parent.name == "Weapon" && (iconName.Contains("Sword") || iconName.Contains("Bow")))
{
string[] splitStr = { "_", " " };
string[] splitIconName = iconName.Split(splitStr, System.StringSplitOptions.RemoveEmptyEntries);
string splitTest = splitIconName[1];
Item foundItem = Manager.Inven.Find(s => s == splitIconName[1]);
FlatBufferBuilder builder = new FlatBufferBuilder(1024);
var equip = C_EQUIP_ITEM.CreateC_EQUIP_ITEM(builder, …
```
> [ADD] 클라이언트 장비 착용에 따른 스킬 적용

- 2D_MMO_Server/GameServer/ClientSession.cpp
- 2D_MMO_Server/GameServer/GameRoom.cpp
- 2D_MMO_Server/GameServer/GameRoom.h
- 2D_MMO_Server/GameServer/GameServer.cpp
- 2D_MMO_Server/GameServer/PacketHandler.cpp
- 2D_MMO_Server/GameServer/PacketHandler.h
- 2D_MMO_Server/GameServer/PacketManager.cpp
- 2D_MMO_Server/GameServer/Player.h
- Common/fbs/InGame.fbs
- Common/fbs/Protocol.fbs
게임 서버에서 맵 전환 처리
어떤 변경 사항이 있나요?
* 패킷 교환 흐름
1. 클라이언트에서 플레이어가 맵 전환이 필요한 좌표에 위치
2. C_CHANGE_MAP 패킷을 통해 현재 좌표와 맵 아이디를 서버로 전송
3. 서버에서 클라이언트로부터 받은 정보를 이용해 바꿔야 할 맵 아이디와 다음 맵에서 스폰해야 할 플레이어의 좌표를 설정
4. 현재 맵(게임 룸)에서 플레이어를 나가게 하고 바꿔야 할 맵(게임 룸)에 플레이어 입장
5. SC_CHANGE_MAP 패킷을 통해 전환해야 할 맵 아이디를 클라이언트로 전송
6. 클라이언트에서 서버로부터 받은 정보를 이용해 맵 전환
<br>
* C_CHANGE_MAP 패킷 처리
```
void GameRoom::HandleChangeMap(shared_ptr<Player> player, const C_CHANGE_MAP* changeMapPkt)
{
if (player == nullptr)
{
return;
}
// 전환될 맵에서 스폰할 좌표
int spawnX = 0;
int spawnY = 0;
if (changeMapPkt->mapId() == 1)
{
if ((changeMapPkt->posX() == -18 || changeMapPkt->posX() == -17 || changeMapPkt->posX() == -16) && changeMapPkt->posY() == 15)
{
player->SetMapId(5); // 5번 맵 입장을 위한 세팅
spawnX = -3;
spawnY = -20;
}
// -- 생략 --
}
WRITE_LOCK;
// 현재 맵(게임 …
```
> [ADD] 서버 맵 전환 처리
